# -*- coding: utf-8 -*-
"""projectno 1.py(1)(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MevMTbhlqkMwvSv8_sF1DecQ-d6KPRQq

## Project no 1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("sales.csv", parse_dates=["Date"])
df

# Remove closed stores (Sales = 0)
df = df[df["Open"] == 1]
df

# Monthly Sales Trend (Line Chart)

monthly_sales = df.groupby("Month")["Sales"].sum()

plt.figure(figsize=(12,5))
monthly_sales.plot(marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("monthly_sales.png")
plt.show()
monthly_sales

# Sales by Day of Week (Bar Chart)
dow_sales = df.groupby("DayOfWeek")["Sales"].mean()
plt.figure(figsize=(8,5))
sns.barplot(x=dow_sales.index, y=dow_sales.values)
plt.title("Average Sales by Day of Week")
plt.xlabel("Day Of Week (1=Mon, 7=Sun)")
plt.ylabel("Average Sales")
plt.tight_layout()
plt.savefig("sales_by_dayofweek.png")
plt.show()
dow_sales

#Promo Impact (Category Comparison)
promo_sales = df.groupby("Promo")["Sales"].mean()

plt.figure(figsize=(6,5))
sns.barplot(x=promo_sales.index, y=promo_sales.values)
plt.title("Average Sales: Promo vs No Promo")
plt.xlabel("Promo (0=No, 1=Yes)")
plt.ylabel("Average Sales")
plt.tight_layout()
plt.savefig("promo_sales.png")
plt.show()

# Pie Chart – Promo Share
promo_count = df["Promo"].value_counts()

plt.figure(figsize=(6,6))
plt.pie(promo_count, labels=["Promo", "No Promo"], autopct="%1.1f%%")
plt.title("Promo Distribution")
plt.savefig("promo_distribution.png")
plt.show()

